# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.abstinence:
        class: SimpleHabits\Infrastructure\Domain\Model\Abstinence\DoctrineAbstinenceRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    app.create_new_abstinence_handler:
        class: SimpleHabits\Application\Handler\CreateNewAbstinenceHandler
        arguments:
            - '@app.repository.abstinence'
        tags:
            - { name: tactician.handler, command: SimpleHabits\Application\Command\CreateNewAbstinenceCommand }